### ISSUE TITLE
Suggestion: 2FA (KeePass + Yubikey)

### ISSUE THREAD

**Issue by mradkov** [OffcierCia/Crypto-OpSec-SelfGuard-RoadMap#2]
For 2FA one can use KeePass + Yubikey as well.

KeePass allows setting up TOTP to any entry in your `.kdbx` file. Yubikey could be used in company with KeePass to add a bit of entropy on each re-encryption when adding an entry in your db file.

references:
- https://developers.yubico.com/Developer_Program/Guides/Touch_triggered_OTP.html
- https://www.reddit.com/r/KeePass/comments/opx34q/keepassxc_and_yubikeys_setting_up_the/
- https://github.com/keepassxreboot/keepassxc/discussions/6344

**Comment by OffcierCia** [comment]
Great tip!

**Comment by OffcierCia** [comment]
Added: https://github.com/OffcierCia/Crypto-OpSec-SelfGuard-RoadMap#problem-2
